[package]
lang = 'bash'
type = 'lib'
name = 'bash-term'
description = 'Bash library for terminal escape sequences'
slug = ['term']
version = '0.6.2'
authors = ['Edwin Kofler <edwin@kofler.dev>']

[run]
dependencies = ['https://github.com/hyperupcall/bash-core@v0.11.0']
binDirs = []
sourceDirs = ['pkg/src/public', 'pkg/src/util']
builtinDirs = []
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]
errexit = 'on'
pipefail = 'on'

[run.shoptOptions]
extglob = 'on'
nullglob = 'on'
shift_verbose = 'on'
