[package]
type = 'bash'
name = 'bash-term'
slug = ['term', 'btput']
version = '0.3.0'
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = ''

[run]
dependencies = []
binDirs = []
sourceDirs = ['pkg/src/public']
builtinDirs = []
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]
errexit = 'on'
pipefail = 'on'

[run.shoptOptions]
nullglob = 'on'
shift_verbose = 'on'
